### ISSUE TITLE
[Feature ⭐] 명령어 핸들러 추가

### ISSUE THREAD

**Issue by scarf005** [exciting-IRC/IRC#57]
- [x] OPER `<user> <password>`
- [x] KILL `<nickname> <comment>`
- [x] QUIT `[ <Quit Message> ]`
- [x] JOIN `( <channel> *( "," <channel> ) [ <key> *( "," <key> ) ] ) | "0"`
- [ ] PART `<channel> *( "," <channel> ) [ <Part Message> ]`
- [x] PRIVMSG `<receiver>{,<receiver>} <text to be sent>`
- [x] PING `<server1> [ <server2> ]`
- [ ] PONG `<server> [ <server2> ]`
- [x] PASS `<password>`
- [x] NICK `<nickname>`
- [x] USER `<username> <hostname> <servername> <realname>`

**Comment by 42-cjeon** [comment]
- [ ] OPER <user> <password>

- [ ] KILL <nickname> <comment>

- [ ] QUIT [ <Quit Message> ]

- [ ] JOIN ( <channel> *( "," <channel> ) [ <key> *( "," <key> ) ] ) | "0"

- [ ] PART <channel> *( "," <channel> ) [ <Part Message> ]

- [ ] PRIVMSG <receiver>{,<receiver>} <text to be sent>

- [ ] PING <server1> [ <server2> ]

- [ ] PONG <server> [ <server2> ]

- [ ] PASS <password>

- [ ] NICK <nickname>

- [ ] USER <username> <hostname> <servername> <realname>
